name: how_much_app
description: "A platform that generates a pricing proposal for developers based on their experiences and skillset"


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_gen: ^5.8.0
  injectable: ^2.5.0
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  flutter_animate: ^4.5.2
  rename: ^3.0.2
  auto_size_text: ^3.0.0
  hugeicons: ^0.0.7
  iconsax: ^0.0.8
  gif: ^2.3.0
  get_it: ^8.0.3
  freezed_annotation: ^2.0.1
  formz: ^0.8.0
  auto_route: ^5.0.0
  nested: ^1.0.0
  provider: ^6.1.2
  form_validator: ^2.1.1
  pinput: ^5.0.1
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.4.2
  flutter_gen_runner: ^5.8.0
  freezed: ^2.3.2
  auto_route_generator: ^5.0.0

flutter:
  
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/icons/
    - assets/png/
  
  
  fonts:
  - family: Urbanist
    fonts:
    - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
      weight: 400
      style: normal
    - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
      weight: 500
      style: normal
    - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
      weight: 600
      style: normal
    - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
      weight: 700
      style: normal
    - asset: assets/fonts/urbanist/Urbanist-ExtraBold.ttf
      weight: 800
      style: normal
  
  
  
